
[module]
  [module.hugoVersion]
    extended = false
    min = "0.55.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true

[blackfriday]
    extensions = ["hardLineBreak"]
    
[outputs]
section = ["HTML", "RSS", "JSON"]

    [menu]

      [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/mission/"
        weight = 10
          [[menu.main]]
            identifier = "mission"
            name = "Mission"
            url = "/about/mission"
            parent = "about"
            weight = 10
          [[menu.main]]
            identifier = "people"
            name = "People"
            url = "/about/people"
            parent = "about"
            weight = 20
          [[menu.main]]
            identifier = "contact"
            name = "Contact"
            url = "/about/contact"
            parent = "about"
            weight = 30
        
      [[menu.main]]
        identifier = "programs"
        name = "Programs"
        url = "/programs/projects"
        weight = 20
          [[menu.main]]
            identifier = "projects"
            name = "Projects"
            url = "/programs/projects/"
            parent = "programs"
            weight = 10
          [[menu.main]]
            identifier = "grants"
            name = "Grants"
            url = "/programs/grants/"
            parent = "programs"
            weight = 20

      [[menu.main]]
        identifier = "community"
        name = "Community"
        url = "/community/events/"
        weight = 30
          [[menu.main]]
            identifier = "blog"
            name = "Blog"
            url = "https://omsf.substack.com/"
            parent = "community"
            weight = 10
          [[menu.main]]
            identifier = "events"
            name = "Events"
            url = "/community/events/"
            parent = "community"
            weight = 30
          [[menu.main]]
            identifier = "jobboard"
            name = "Job Board"
            url = "/community/Jobboard/"
            parent = "community"
            layout = "jobboard"
            weight = 40
          [[menu.main]]
            identifier = "playbooks"
            name = "Playbooks"
            url = "https://playbooks.omsf.io"
            parent = "community"
            weight = 50
          [[menu.main]]
            identifier = "directory"
            name = "Software Directory"
            url = "https://directory.omsf.io"
            parent = "community"
            weight = 60

        [[menu.main]]
        identifier = "involved"
        name = "Get Involved"
        url = "/involved/bringproject/"
        weight = 50
              [[menu.main]]
              identifier = "bringproject"
              name = "Projects"
              url = "/involved/bringproject/"
              parent = "involved"
              weight = 10
            [[menu.main]]
              identifier = "contributor"
              name = "Academics"
              url = "/involved/contributor/"
              parent = "involved"
              weight = 20
            [[menu.main]]
              identifier = "industrypartner"
              name = "Industry"
              url = "/involved/industrypartner/"
              parent = "involved"
              weight = 30
            [[menu.main]]
              identifier = "donate"
              name = "Donations"
              url = "/involved/donate/"
              parent = "involved"
              weight = 40
          
      [[menu.main]]
        identifier = "resources"
        name = "Resources"
        url = "/resources/fiscalsponsorship/"
        weight = 60
          [[menu.main]]
              identifier = "fiscalsponsorship"
              name = "What We Do"
              url = "/resources/fiscalsponsorship/"
              parent = "resources"
              weight = 10
          [[menu.main]]
              identifier = "documentation"
              name = "Documentation"
              url = "/resources/documentation/"
              parent = "resources"
              weight = 20
          [[menu.main]]
              identifier = "bylaws"
              name = "Bylaws"
              url = "/resources/bylaws/"
              parent = "resources"
              weight = 30
