name: Cleanup staging
description: Cleanup staging environment; this occurs on PR merge or close

on:
  pull_request:
    types: [closed]

jobs:
  cleanup-staging:
    uses: omsf/static-site-tools/.github/workflows/cleanup-cloudflare.yaml@main
    with:
      pr_number: ${{ github.event.pull_request.number }}
      project_name: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
